spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:testdb
    username: sa
    password: '{cipher}AQBnsI7MMqiPh0pt6tj4tn5OLa2+NMAfvNtcUaI+OAnbuLw+oy0yVSWhGsf2Ti1Vqeuo9dmiyc+iySlLT1W+yPOX4sG0EXzTT38fiIn+G5FGMrs5s5jdyq0UVnsHoGdbwouADNiHg2MWZRyeQk6PxlUx6NtunXv5ohhSW6957/9VwvltwYL/pEzMLtmGMexWOG6dMQQl44iJbDIURqJNmKREpPqQJgRbBJnlbRgKWRjTz9rZMBvkuU3TZIY9DXNgvwgwEBenAHpoYF8sYPGwduLzndvSHAmXYX0vSvVZ30YvQ2mG8pekW0hMw7NvPImbvlG3KXaLqRZWK+Mc0W4AsjVuTfdP80uueg2De9vKnC9I9su9dXhVdeGMIW/dXzeBa7M='

# token: 
#   expiration_time: 864000000
#   secret: '{cipher}AQDCJl87BIdlbGNh9MNph6fSgYSx8IxMh8X7bDY+g0/MIVGpZqH1lqMs+kxEUGTfprNtoZrJBRZj7ImbMBU2eFhQvuGrVcQQf+015ftM3rui35pJ5o6U7iTrLPPGj3ptf1CBnqpwhZ1oDzLGrCEF6/PsVKnzywM1DG/r2/w5VP/kT7KxLmpUxkTOKna33G0bdQ4R8/Moyg6rL//qUKTLDT5X9ZQJKc6BAKX5EENoW7pwjefABuCezKKEdjTR5ZSHBmvObpfgiVrZmUAjtBKiVfANQudI68JVk9S6CuG11XEYSczCgGNPMz73etSFruuBEM+5JftdWf5dhmF+r6GPKCW0n8Z8BIERemrYNxdRziEHmHS9Laf9k21qZj6J9TBY6F/HFtlLoT0JMa6HXx/HdMJN'


order_service:
 url: http://ORDER-SERVICE/order-service/%s/orders
 exception: 
  orders_is_empty: There is no item.

gateway:
  ip: 172.18.0.5
